---

- name: Get stats of python3  # noqa: command-instead-of-shell
  ansible.builtin.shell: command -v python3
  register: python3_bin
  changed_when: false

- name: Get stats of poetry  # noqa: command-instead-of-shell
  ansible.builtin.shell: command -v poetry
  register: poetry_bin
  changed_when: false
  failed_when: false

- name: Poetry debug output
  ansible.builtin.debug:
    msg: "{{ poetry_bin }}"
    verbosity: 1

- name: Set poetry_exists fact
  ansible.builtin.set_fact:
    poetry_exists: "{{ poetry_bin.rc == 0 }}"

- name: Debug output
  ansible.builtin.debug:
    msg: "{{ poetry_exists }}"
    verbosity: 1
